using TMPro;
using UnityEngine;
using UnityEngine.UI;

public class BossHPUI : MonoBehaviour
{
    private ZombieStat target;

    [SerializeField] private Slider hpSlider; // ğŸ¯ Slider ì‚¬ìš©
    [SerializeField] private TMP_Text nameText; // ğŸ¯ Slider ì‚¬ìš©

    public void Init(ZombieStat target)
    {
        this.target = target;
        
        nameText.text = target.name;
        
        if (hpSlider != null)
        {
            hpSlider.maxValue = target.maxHealth;
        }
    }

    void LateUpdate()
    {
        if (target == null) return;
    
        // ì²´ë ¥ ë°˜ì˜
        if (hpSlider != null)
        {
            hpSlider.value = target.health;
        }
    }
}